-- Modify "users" table
ALTER TABLE "users" ADD COLUMN "created_at" timestamptz NOT NULL, ADD COLUMN "updated_at" timestamptz NOT NULL;
-- Create "events" table
CREATE TABLE "events" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "description" character varying NULL, "event_slug" character varying NOT NULL, "location" text NOT NULL, "image_url" character varying NOT NULL, "contract_address" character varying NULL, "transaction_hash" character varying NULL, "block_number" character varying NULL, "created_at" timestamptz NOT NULL, "modified_at" timestamptz NOT NULL, "user_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "events_users_events" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "events_event_slug_key" to table: "events"
CREATE UNIQUE INDEX "events_event_slug_key" ON "events" ("event_slug");
-- Create index "events_name_key" to table: "events"
CREATE UNIQUE INDEX "events_name_key" ON "events" ("name");
-- Create "attendees" table
CREATE TABLE "attendees" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "ticket_id" bigint NOT NULL, "event_id" bigint NOT NULL, "user_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "attendees_events_attendees" FOREIGN KEY ("event_id") REFERENCES "events" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "attendees_users_attendee_tickets" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "tickets" table
CREATE TABLE "tickets" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "description" character varying NOT NULL, "ticket_slug" character varying NOT NULL, "mint_price" character varying NOT NULL, "quantity" bigint NOT NULL, "contract_address" character varying NULL, "transaction_hash" character varying NULL, "block_number" character varying NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "event_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "tickets_events_tickets" FOREIGN KEY ("event_id") REFERENCES "events" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "tickets_ticket_slug_key" to table: "tickets"
CREATE UNIQUE INDEX "tickets_ticket_slug_key" ON "tickets" ("ticket_slug");
